// Generated by `node scripts/backtest.mjs --calibrate` — do not edit by hand.
// Daily backtest, 10 years to 2026-10-04. For a predicted 14-day change of x
// ($/gal), p = share of days the price was lower a week later, move = the
// average actual 7-day change ($/gal). See docs/BACKTEST.md ("Odds").
export const ODDS = {
  regular: [
    {"x":-0.1266,"p":0.835,"move":-0.0439},
    {"x":-0.0496,"p":0.743,"move":-0.014},
    {"x":-0.0298,"p":0.703,"move":-0.012},
    {"x":-0.0151,"p":0.619,"move":-0.0033},
    {"x":-0.0049,"p":0.563,"move":-0.0007},
    {"x":0.0052,"p":0.511,"move":0.0045},
    {"x":0.015,"p":0.448,"move":0.0109},
    {"x":0.0297,"p":0.377,"move":0.0182},
    {"x":0.0499,"p":0.299,"move":0.022},
    {"x":0.1215,"p":0.23,"move":0.0437},
  ],
  midgrade: [
    {"x":-0.1262,"p":0.824,"move":-0.0414},
    {"x":-0.0496,"p":0.722,"move":-0.0131},
    {"x":-0.0298,"p":0.688,"move":-0.0108},
    {"x":-0.015,"p":0.617,"move":-0.0026},
    {"x":-0.0049,"p":0.557,"move":-0.0006},
    {"x":0.0052,"p":0.507,"move":0.0045},
    {"x":0.0151,"p":0.438,"move":0.0105},
    {"x":0.0297,"p":0.377,"move":0.0176},
    {"x":0.0498,"p":0.302,"move":0.0216},
    {"x":0.1211,"p":0.231,"move":0.0427},
  ],
  premium: [
    {"x":-0.126,"p":0.827,"move":-0.0417},
    {"x":-0.0496,"p":0.718,"move":-0.0125},
    {"x":-0.0299,"p":0.691,"move":-0.0108},
    {"x":-0.0151,"p":0.611,"move":-0.0028},
    {"x":-0.0048,"p":0.561,"move":-0.0005},
    {"x":0.0051,"p":0.505,"move":0.0046},
    {"x":0.0151,"p":0.434,"move":0.0115},
    {"x":0.0297,"p":0.37,"move":0.018},
    {"x":0.0498,"p":0.296,"move":0.0216},
    {"x":0.1211,"p":0.225,"move":0.0434},
  ],
  diesel: [
    {"x":-0.1281,"p":0.882,"move":-0.0459},
    {"x":-0.05,"p":0.788,"move":-0.014},
    {"x":-0.0299,"p":0.721,"move":-0.0095},
    {"x":-0.0147,"p":0.609,"move":-0.004},
    {"x":-0.0047,"p":0.538,"move":0.0073},
    {"x":0.0049,"p":0.478,"move":0.0094},
    {"x":0.015,"p":0.397,"move":0.0107},
    {"x":0.0298,"p":0.364,"move":0.0115},
    {"x":0.0496,"p":0.293,"move":0.0155},
    {"x":0.1312,"p":0.203,"move":0.0622},
  ],
};

// Per-area reliability k (0.3–1): the odds shown for an area are scaled toward
// 50/50 as 0.5 + k·(p − 0.5), and the average move by k. Areas with sharp,
// irregular price cycles score lowest. See docs/BACKTEST.md ("Odds").
export const SKILL = {
  regular: {"NUS":1,"YBOS":1,"YORD":0.75,"YCLE":0.54,"YDEN":0.91,"Y44HO":1,"Y05LA":1,"YMIA":1,"Y35NY":1,"Y05SF":0.94,"Y48SE":1,"SCA":1,"SCO":0.96,"SFL":1,"SMA":1,"SMN":1,"SNY":1,"SOH":0.4,"STX":1,"SWA":1,"R1X":1,"R1Y":1,"R1Z":1,"R10":1,"R20":0.92,"R30":1,"R40":0.99,"R50":1,"R5XCA":1},
  midgrade: {"NUS":1,"YBOS":1,"YORD":0.77,"YCLE":0.56,"YDEN":0.93,"Y44HO":1,"Y05LA":1,"YMIA":1,"Y35NY":1,"Y05SF":0.93,"Y48SE":1,"SCA":1,"SCO":0.99,"SFL":1,"SMA":1,"SMN":1,"SNY":1,"SOH":0.42,"STX":1,"SWA":1,"R1X":1,"R1Y":1,"R1Z":1,"R10":1,"R20":0.89,"R30":1,"R40":0.92,"R50":1,"R5XCA":1},
  premium: {"NUS":1,"YBOS":1,"YORD":0.79,"YCLE":0.57,"YDEN":0.95,"Y44HO":1,"Y05LA":1,"YMIA":1,"Y35NY":1,"Y05SF":0.94,"Y48SE":0.98,"SCA":1,"SCO":0.98,"SFL":1,"SMA":1,"SMN":1,"SNY":1,"SOH":0.42,"STX":1,"SWA":1,"R1X":1,"R1Y":1,"R1Z":1,"R10":1,"R20":0.96,"R30":1,"R40":0.97,"R50":1,"R5XCA":1},
  diesel: {"NUS":1,"SCA":1,"R1X":1,"R1Y":1,"R1Z":1,"R10":1,"R20":0.97,"R30":1,"R40":0.95,"R50":1,"R5XCA":1},
};
